# Generated by Django 6.0.5 on 2026-05-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold_pct', models.FloatField(default=80.0)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('frame_skip', models.IntegerField(default=5)),
                ('yolo_model_path', models.CharField(default='models/sku/individual_products.pt', max_length=500)),
                ('cnn_model_path', models.CharField(default='models/classifier/best_lightweight_cnn.pth', max_length=500)),
                ('void_model_path', models.CharField(default='models/void/void_0,95_best_one.pt', max_length=500)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('void_confidence_threshold', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ended', 'Ended'), ('failed', 'Failed')], default='running', max_length=10)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.cameraconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_products', models.IntegerField(default=0)),
                ('missing_products', models.IntegerField(default=0)),
                ('void_detections', models.IntegerField(default=0)),
                ('stock_pct', models.FloatField(default=0.0)),
                ('fps', models.FloatField(default=0.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('summary_json', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='monitoring.monitoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_pct_at_trigger', models.FloatField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.alertrule')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringsession')),
            ],
        ),
    ]
